[build]
  command = "npm install && npm run build"   # This runs `npm install` and then `npm run build`
  publish = "build"                          # This is where the static files from the React app will be output
  functions = "built-lambda"                 # This is where Netlify will look for lambda functions

[functions]
  directory = "built-lambda"                 # Ensure this matches your lambda output directory